@host=https://localhost:7116

POST {{host}}/auth/register
content-type: application/json

{
    "firstName": "Ashen",
    "lastName": "Disanayaka",
    "email": "ashenupendra@gmail.com",
    "password": "Word@pass1234"
}


### next request

POST {{host}}/auth/register
content-type: application/json

{
    "firstName": "Aparna",
    "lastName": "Hetti",
    "email": "ashenupendra@gmail.com",
    "password": "Word@pass1234"
}